language: python
python:
  - "2.7"
  - "3.4"
env:
  - DJANGO_VERSION=1.9.1
install:
  - pip install -q -e .
  - pip install django==$DJANGO_VERSION
script: django-admin.py test --settings=progressbarupload.test_settings progressbarupload
