language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.5.1
install:
  - pip install -q -e . --use-mirrors
  - pip install -r requirements-tests.txt django==$DJANGO_VERSION
script: django-admin.py test --settings=progressbarupload.test_settings progressbarupload